# =================================
# = Spring
# =================================
spring:
  datasource:
    url: jdbc:mysql://realmeet-db.cql1m87a4klv.sa-east-1.rds.amazonaws.com:3306/realmeet?&severTimezone=UTC&useSSL=false
    username: admin
